### ISSUE TITLE
3D Download should have a file extension

### ISSUE THREAD

**Issue by martintaraz** [Siegler-von-Catan/SiegelWebapp#1]
When clicking on "3D Druck" on this page http://siegeleditor.paulmethfessel.com/siegel.html?s=2
I get a File without an extension, even though it is a valid stl file
That might lead to confusion and certain editors might not be able to open it

**Comment by leogeier** [comment]
The 3D-Druck download has since been changed. Now it is a zip containing the stl files along with some others. All, including the archive itself, have an extension.
