### ISSUE TITLE
Siegel Name is not Displayed, instead there is a Placeholder

### ISSUE THREAD

**Issue by martintaraz** [Siegler-von-Catan/SiegelWebapp#2]
At http://siegeleditor.paulmethfessel.com/siegel.html?s=2 there is a Placeholder Text below the Siegel
![image](https://user-images.githubusercontent.com/26792474/105110252-85cca700-5abe-11eb-877e-46caff774b7c.png)

**Comment by leogeier** [comment]
Fixed in the current version.
